version: "3.8"

services:
  streamlit-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    environment:
      - HUME_API_KEY=
      - HUME_SECRET_KEY=
      - TWILIO_ACCOUNT_SID=
      - TWILIO_AUTH_TOKEN=
      - TWILIO_RECIPIENT=
      - GOOGLE_API_KEY=
      - CHROMA_HOST=chromadb
      - CHROMA_CLIENT_AUTH_CREDENTIALS=test-token
      - CHROMA_AUTH_TOKEN_TRANSPORT_HEADER=X-Chroma-Token
    volumes:
      - .:/app

  chromadb:
    image: chromadb/chroma:latest
    ports:
      - "8000:8000"
    environment:
      - CHROMA_SERVER_AUTHN_CREDENTIALS=test-token
      - CHROMA_SERVER_AUTHN_PROVIDER=chromadb.auth.token_authn.TokenAuthenticationServerProvider
      - CHROMA_AUTH_TOKEN_TRANSPORT_HEADER=X-Chroma-Token
    volumes:
      - chromadb_data:/data 

volumes:
  chromadb_data:
    driver: local